data_gov:
  api_key: "579b464db66ec23bdd00v46e44ce4aad7209ff7b23ac571b"
llm_provider: gemini
google_api_key: "AIzaSyDBPeUYO49vDsxRvLzR4otQ"   # api_key: "AIzaSyCdSMv3dccjY7Ah2c AIzaSyDMvsH4iXvt0ItKyRZIQujOI"

embedding_model: "models/embedding-001"
embedding_provider: "huggingface"  # Options: "google" or "huggingface"
huggingface_model: "sentence-transformers/all-MiniLM-L6-v2"
chat_model: "models/gemini-pro-latest"



